// Local QA only. This file is never embedded by tools/build.mjs or deployed.
import fs from 'node:fs';
import vm from 'node:vm';
import {DatabaseSync} from 'node:sqlite';
import worker from '../worker/index.js';
export function previewPlugin(){
 const db=new DatabaseSync(':memory:');db.exec(fs.readFileSync('drizzle/0000_foamy_luckman.sql','utf8'));
 const env={DB:{prepare(sql){return {bind(...args){return {first:async()=>db.prepare(sql).get(...args),run:async()=>({meta:{changes:db.prepare(sql).run(...args).changes}})};}};}}};
 const ctx=vm.createContext({window:{}});for(const f of ['curriculum','enrichment','fpga/catalog','fpga/content','fpga/neutral','fpga/foundation','fpga/progress','project/catalog','project/model'])vm.runInContext(fs.readFileSync('public/'+f+'.js','utf8'),ctx);
 const {IC_COURSE,IC_FPGA_CATALOG:C,IC_FPGA_PROGRESS:P,IC_FPGA_CONTENT:D}=ctx.window;
 const fixture=(main,fpga)=>{const p={schema:1,course:'ic-pathway',last:'fpga',lessons:{},acceptance:{},ultra:{},...P.normalize({})};for(const l of IC_COURSE.LESSONS.slice(0,main))p.lessons[l.id]={draft:'QA fixture: existing legacy completion',choice:l.quiz.correct,quizPassed:true,completed:true};for(const m of C.modules.slice(0,fpga))p.fpga.lessons[m.id]={...P.blankLesson(),guided:'QA fixture guided',independent:'QA fixture independent',choices:D[m.id].quiz.map(q=>q.correct),quizPassed:true,checks:[true,true,true],completed:true};return p;};
 return {name:'ic-preview-api',configureServer(server){server.middlewares.use(async(req,res,next)=>{try{
 const url=new URL(req.url,'http://terminal.local:4173');
 if(url.pathname==='/__qa'&&req.method==='GET'){res.setHeader('Content-Type','text/html;charset=utf-8');res.end(`<!doctype html><html lang="zh"><meta charset="utf-8"><title>IC Pathway preview QA</title><style>body{font:16px system-ui;margin:12px}button{padding:10px;margin:4px}iframe{display:block;height:850px;border:1px solid #999;max-width:100%}</style><h1>Preview-only QA scenarios</h1><p>Synthetic accounts and records. No production data. Select a scenario, then open the course.</p><form method="POST" action="/__qa/fixture"><button name="scenario" value="locked">Fresh learner</button><button name="scenario" value="eight">Main 1–8 completed</button><button name="scenario" value="ultra">Ultra LED available</button><button name="scenario" value="full">All lessons available</button><button name="scenario" value="resume">Resume QA account A</button><button name="scenario" value="other">Separate QA account B</button></form><p><a href="/">Open course</a></p><button data-width="390">Mobile 390</button><button data-width="768">Tablet 768</button><button data-width="1440">Desktop 1440</button><iframe title="Responsive course preview" width="390" src="/#fpga"></iframe><script>document.querySelectorAll('[data-width]').forEach(b=>b.onclick=()=>document.querySelector('iframe').width=b.dataset.width);</script></html>`);return;}
 if(url.pathname==='/__qa/fixture'&&req.method==='POST'){let body='';for await(const c of req)body+=c;const scenario=new URLSearchParams(body).get('scenario');const id=scenario==='other'?'qa-b':'qa-a';const cases={locked:[0,0],eight:[8,0],ultra:[16,11],full:[24,21]};if(cases[scenario]){const data=fixture(...cases[scenario]);db.prepare('INSERT INTO learning_progress (user_id,data,revision,updated_at) VALUES (?,?,1,?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data,revision=learning_progress.revision+1,updated_at=excluded.updated_at').run(id,JSON.stringify(data),new Date().toISOString());}if(scenario==='other'&&!db.prepare('SELECT user_id FROM learning_progress WHERE user_id=?').get(id))db.prepare('INSERT INTO learning_progress VALUES (?,?,1,?)').run(id,JSON.stringify(fixture(0,0)),new Date().toISOString());res.setHeader('Set-Cookie',`qa-account=${id}; Path=/; SameSite=Lax`);res.setHeader('Location','/');res.statusCode=303;res.end();return;}
 if(url.pathname.startsWith('/api/')){const headers=new Headers();for(const [k,v]of Object.entries(req.headers))if(v)headers.set(k,Array.isArray(v)?v.join(','):v);headers.delete('oai-authenticated-user-id');headers.delete('oai-authenticated-user-email');const id=(req.headers.cookie||'').match(/(?:^|; )qa-account=(qa-[ab])(?:;|$)/)?.[1];if(id){headers.set('oai-authenticated-user-id',id);headers.set('oai-authenticated-user-email','Preview fixture '+id);}let body='';for await(const c of req)body+=c;const response=await worker.fetch(new Request(url,{method:req.method,headers,body:body||undefined}),env);res.statusCode=response.status;for(const [k,v]of response.headers)res.setHeader(k,v);res.end(await response.text());return;}
 next();}catch(error){server.config.logger.error(error.stack);res.statusCode=500;res.end('Preview failure');}});}};
}
